version: 2

models:
  - name: stg_customers
    description: holla
    tags:['pepsi','sprite']
    columns:
      - name: customer_id
        description: Lola is awesome!
        tests:
          - unique
          - not_null
        tags:
          - Today is Thursday

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']

  - name: stg_customer_orders
